name: SeniorProject
channels:
  - defaults
dependencies:
  - asgiref=3.8.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.14
  - python-tzdata=2023.3
  - setuptools=72.1.0
  - sqlite=3.45.3
  - sqlparse=0.4.4
  - tk=8.6.14
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - django==4.2.9
      - django-theme-pixel==1.0.3
      - gunicorn==21.2.0
      - packaging==24.1
      - python-dotenv==1.0.1
      - str2bool==1.1
      - whitenoise==6.6.0